version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "pip install -r docs/requirements.txt"
      - "pip install ."
      - pip install "mkdocs-material[imaging]"
      - "mkdocs build"

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false